from django.urls import path
import learn.views
urlpatterns = [
    path('', learn.views.home , name ='home'),
    path('home', learn.views.home , name ='home'),
    path('h_reg_msg', learn.views.h_reg_msg , name ='h_reg_msg'),
    path('h_blog_add', learn.views.h_blog_add , name ='h_blog_add'),
    path('h_blog_view', learn.views.h_blog_view , name ='h_blog_view'),
    path('news', learn.views.news, name ='news'),
    path('about', learn.views.about, name ='about'),
    path('add', learn.views.add, name ='add'),
    path('contact', learn.views.contact, name ='contact'),
    path('student', learn.views.student, name ='student'),
    path('subject', learn.views.subject, name ='subject'),
    path('teacher', learn.views.teacher, name ='teacher'),
    path('view', learn.views.view, name ='view'),
    path('login', learn.views.login, name ='login'),
    path('admin_register', learn.views.admin_rg, name ='admin_register'),
    path('s_booked_course', learn.views.s_booked_course, name='s_booked_course'),
    path('student_home', learn.views.student_home, name='student_home'),
    path('s_bk_course_course', learn.views.s_bk_course_course, name='s_bk_course_course'),
    path('s_bk_course_subject', learn.views.s_bk_course_subject, name='s_bk_course_subject'),
    path('s_bk_course_teacher', learn.views.s_bk_course_teacher, name='s_bk_course_teacher'),
    path('s_bk_course_book/<id>', learn.views.s_bk_course_book, name='s_bk_course_book'),
    path('s_bk_course_bktaecher', learn.views.s_bk_course_bkteacher, name='s_bk_course_bkteacher'),
    path('s_myprofile', learn.views.s_myprofile, name='s_myprofile'),
    path('s_download_certificate', learn.views.s_download_certificate, name='s_download_certificate'),
    path('s_feedback', learn.views.s_feedback, name='s_feedback'),
    path('s_change_password', learn.views.s_change_password, name='s_change_password'),
    path('s_messages', learn.views.s_messages, name='s_messages'),
    path('s_booked_ac/<id>/<ikm>/<sub>', learn.views.s_booked_ac, name='s_booked_ac'),
    path('s_booked_ac1', learn.views.s_booked_ac1, name='s_booked_ac1'),
    path('s_booked_comp', learn.views.s_booked_comp, name='s_booked_comp'),
    path('s_exam_noti', learn.views.s_exam_noti, name='s_exam_noti'),
    path('s_start_test', learn.views.s_start_test, name='s_start_test'),
    path('s_save_exam', learn.views.s_save_exam, name='s_save_exam'),
    path('s_msg_sent', learn.views.s_msg_sent, name='s_msg_sent'),
    path('s_msg_del/<id>', learn.views.s_msg_del, name='s_msg_del'),
    path('s_msg_reply/<id>', learn.views.s_msg_reply, name='s_msg_reply'),
    path('s_exam_result', learn.views.s_exam_result, name='s_exam_result'),



    path('teacher_home', learn.views.teacher_home, name='teacher_home'),
    path('t_chapter', learn.views.t_chapter, name='t_chapter'),
    path('t_change_password', learn.views.t_change_password, name='t_change_password'),
    path('t_chapter_content', learn.views.t_chapter_content, name='t_chapter_content'),
    path('t_ch_con_add_course', learn.views.t_ch_con_add_course, name='t_ch_con_add_course'),
    path('t_ch_con_add_subject', learn.views.t_ch_con_add_subject, name='t_ch_con_add_subject'),
    path('t_ch_con_add_chapter', learn.views.t_ch_con_add_chapter, name='t_ch_con_add_chapter'),
    path('t_ch_con_edit/<id>', learn.views.t_ch_con_edit, name='t_ch_con_edit'),
    path('t_ch_con_delete/<id>', learn.views.t_ch_con_delete, name='t_ch_con_delete'),
    path('t_delete_test', learn.views.t_delete_test, name='t_delete_test'),
    path('t_delete_test1/<id>', learn.views.t_delete_test1, name='t_delete_test1'),
    path('logout', learn.views.logout, name='logout'),
    path('t_messages', learn.views.t_messages, name='t_messages'),
    path('t_msg_del/<id>', learn.views.t_msg_del, name='t_msg_del'),
    path('t_msg_reply/<id>', learn.views.t_msg_reply, name='t_msg_reply'),
    path('t_msg_sent', learn.views.t_msg_sent, name='t_msg_sent'),
    path('t_exam_result', learn.views.t_exam_result, name='t_exam_result'),
    path('t_delete_examresult/<id>', learn.views.t_delete_examresult, name='t_delete_examresult'),
    path('t_schedule_test', learn.views.t_schedule_test, name='t_schedule_test'),
    path('t_schedule_test1', learn.views.t_schedule_test1, name='t_schedule_test1'),
    path('t_schedule_test2', learn.views.t_schedule_test2, name='t_schedule_test2'),
    path('t_attendance', learn.views.t_attendance, name='t_attendance'),
    path('t_student_booked_details', learn.views.t_student_booked_details, name='t_student_booked_details'),
    path('t_bk_st_accept/<id>', learn.views.t_bk_st_accept, name='t_bk_st_accept'),
    path('t_bk_st_reject/<id>', learn.views.t_bk_st_reject, name='t_bk_st_reject'),
    path('t_bk_st_delete/<id>', learn.views.t_bk_st_delete, name='t_bk_st_delete'),
    path('t_notify', learn.views.t_notify, name='t_notify'),
    path('t_student_progress', learn.views.t_student_progress, name='t_student_progress'),
    path('t_subject', learn.views.t_subject, name='t_subject'),
    path('t_update_pr', learn.views.t_update_pr, name='t_update_pr'),
    path('t_delete_subject/<id>/<idd>/<idm>', learn.views.t_delete_subject, name='t_delete_subject'),
    path('t_edit_subject/<id>/<idd>/<idm>', learn.views.t_edit_subject, name='t_edit_subject'),
    path('t_add_subject', learn.views.t_add_subject, name='t_add_subject'),
    path('t_add_chapter_sub', learn.views.t_add_chapter_sub, name='t_add_chapter_sub'),
    path('t_add_chapter_cou', learn.views.t_add_chapter_cou, name='t_add_chapter_cou'),
    path('t_edit_chapter/<id>/<idd>/<idk>/<idm>', learn.views.t_edit_chapter, name='t_edit_chapter'),
    path('t_delete_chapter/<id>/<idd>/<idk>/<idm>', learn.views.t_delete_chapter, name='t_delete_chapter'),



    path('a_about', learn.views.a_about, name='a_about'),
    path('admin_home', learn.views.admin_home, name='admin_home'),
    path('a_updatepr_edit', learn.views.a_updatepr_edit, name='a_updatepr_edit'),
    path('a_block', learn.views.a_block, name='a_block'),
    path('a_block_teach/<id>', learn.views.a_block_teach, name='a_block_teach'),
    path('a_block_stu/<id>', learn.views.a_block_stu, name='a_block_stu'),
    path('a_allow_teach/<id>', learn.views.a_allow_teach, name='a_allow_teach'),
    path('a_allow_stu/<id>', learn.views.a_allow_stu, name='a_allow_stu'),
    path('a_blog_approve/<id>', learn.views.a_blog_approve, name='a_blog_approve'),
    path('a_blog_reject/<id>', learn.views.a_blog_reject, name='a_blog_reject'),
    path('a_blog_delete/<id>', learn.views.a_blog_delete, name='a_blog_delete'),
    path('a_blog', learn.views.a_blog, name='a_blog'),
    path('a_sub_cha_add', learn.views.a_sub_cha_add, name='a_sub_cha_add'),
    path('a_sub_cha_edit/<id>/<idd>/<idt>/<idk>/<pkm>', learn.views.a_sub_cha_edit, name='a_sub_cha_edit'),
    path('a_sub_cha_del/<id>/<idd>/<idt>/<idk>/<pkm>', learn.views.a_sub_cha_del, name='a_sub_cha_del'),
    path('a_sub_chco_edit/<id>', learn.views.a_sub_chco_edit, name='a_sub_chco_edit'),
    path('a_sub_chco_add', learn.views.a_sub_chco_add, name='a_sub_chco_add'),
    path('a_sub_chco_del/<id>', learn.views.a_sub_chco_del, name='a_sub_chco_del'),
    path('a_delete', learn.views.a_delete, name='a_delete'),
    path('a_member', learn.views.a_member, name='a_member'),
    path('a_password_request', learn.views.a_password_request, name='a_password_request'),
    path('a_password_change/<id>', learn.views.a_password_change, name='a_password_change'),
    path('a_subject', learn.views.a_subject, name='a_subject'),
    path('a_sub_edit/<id>/<idd>/<idt>/<pkm>', learn.views.a_sub_edit, name='a_sub_edit'),
    path('a_sub_del/<id>/<idd>/<idt>/<pkm>', learn.views.a_sub_del, name='a_sub_del'),
    path('a_cer_upl', learn.views.a_cer_upl, name='a_cer_upl'),
    path('a_cer_del/<id>', learn.views.a_cer_del, name='a_cer_del'),
    path('a_cer_del_dis', learn.views.a_cer_del_dis, name='a_cer_del_dis'),
    path('a_resign', learn.views. a_resign, name='a_resign'),
    path('a_feedback', learn.views.a_feedback, name='a_feedback'),
    path('a_feed_delete/<id>', learn.views.a_feed_delete, name='a_feed_delete'),
    path('a_guest_msg_del/<id>', learn.views.a_guest_msg_del, name='a_guest_msg_del'),
    path('a_guest_msg', learn.views.a_guest_msg, name='a_guest_msg'),
    path('a_member_msg', learn.views.a_member_msg, name='a_member_msg'),
    path('a_member_msg_del/<id>', learn.views.a_member_msg_del, name='a_member_msg_del'),
    path('a_member_msg_reply/<id>', learn.views.a_member_msg_reply, name='a_member_msg_reply'),
    path('a_member_msg_sent', learn.views.a_member_msg_sent, name='a_member_msg_sent'),









]



